from os.path import join


def grab_output(wildcards):
    f = []
    for tool in config['tools']:
        p = join(tool, config['seq'] + '.gff')
        f.append(p)
    return f

outputs = []
for task in config:
    if task in ['seq', 'genetic_code']:
        continue
    task_config = config[task]
    for rule in task_config:
        if task == 'protein':
            outputs.append('%s.hit' % rule)
        else:
            outputs.append('%s.ok' % rule)
        rule_config = task_config[rule]
        include: '%s.rule' % rule

rule all:
    input:
        outputs

# rule report:
#     input:
#         '{seq}.gff'
#     output:
#         "{seq}.html"
#     run:
#         from snakemake.utils import report
#         shell('touch {output[0]}')



# ruleorder: ncRNA > tRNA > CRISPR
