from os.path import join, basename, abspath


def grab_output(wildcards):
    f = []
    for tool in config['tools']:
        p = join(tool, config['seq'] + '.gff')
        f.append(p)
    return f


outputs = []
for tool in config['tools']:
    outputs.append('%s.ok' % tool)
    tool_config = config['tools'][tool]
    include: '%s.rule' % tool


outputs.append('rest.faa')

rule all:
    input:
        outputs

# rule report:
#     input:
#         '{seq}.gff'
#     output:
#         "{seq}.html"
#     run:
#         from snakemake.utils import report
#         shell('touch {output[0]}')



# ruleorder: ncRNA > tRNA > CRISPR
